### ISSUE TITLE
Docker Build Failing

### ISSUE THREAD

**Issue by CrisFavero** [awslabs/amazon-redshift-utils#635] opened 2022-07-29 15:49 UTC
Steps to reproduce,  from in the directory: `docker build  .`

Log of execution 
```
❯ docker build .                                                            
[+] Building 39.8s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                       0.1s
 => => transferring dockerfile: 624B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => [internal] load metadata for docker.io/library/python:2-slim           1.1s
 => [1/7] FROM docker.io/library/python:2-slim@sha256:6c1ffdff499e29ea663  7.3s
 => => resolve docker.io/library/python:2-slim@sha256:6c1ffdff499e29ea663  0.0s
 => => sha256:6c1ffdff499e29ea663e6e67c9b6b9a3b401d554d2c 1.86kB / 1.86kB  0.0s
 => => sha256:b68d40df862ac07e8955ea0fc0c5454cb4245b6165e 1.16kB / 1.16kB  0.0s
 => => sha256:eeb27ee6b89303f04a917e457eda70d032b1574ec80 7.95kB / 7.95kB  0.0s
 => => sha256:123275d6e508d282237a22fefa5aef822b719a064 27.10MB / 27.10MB  4.3s
 => => sha256:dd1cd66375238ded36eeaea07567a1997f7fd76611a 2.75MB / 2.75MB  1.2s
 => => sha256:0c4e6d630f2cb5403efb04352c40ed72f18843552 19.66MB / 19.66MB  4.6s
 => => sha256:13e9cd8f0ea14403e44c745ea5212658b6600021f6b 2.18MB / 2.18MB  2.0s
 => => extracting sha256:123275d6e508d282237a22fefa5aef822b719a06496444ea  1.4s
 => => extracting sha256:dd1cd66375238ded36eeaea07567a1997f7fd76611a51711  0.2s
 => => extracting sha256:0c4e6d630f2cb5403efb04352c40ed72f1884355253a0cc1  0.9s
 => => extracting sha256:13e9cd8f0ea14403e44c745ea5212658b6600021f6beb6fc  0.2s
 => [internal] load build context                                          1.1s
 => => transferring context: 61.64MB                                       1.1s
 => [2/7] RUN apt-get update && mkdir -p /usr/share/man/man1 /usr/share/m  3.3s
 => [3/7] RUN apt-get install -y libpq-dev postgresql-client gcc          18.2s
 => [4/7] WORKDIR /usr/src/app                                             0.0s
 => [5/7] COPY src/ /usr/src/app/                                          0.2s
 => [6/7] RUN find /usr/src/app -name "*.py"|xargs chmod +x && find /usr/  0.3s
 => ERROR [7/7] RUN pip install -r /usr/src/app/requirements.txt &&     p  8.9s
------
 > [7/7] RUN pip install -r /usr/src/app/requirements.txt &&     pip install -r /usr/src/app/UnloadCopyUtility/requirements.txt:
#11 1.131 DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
#11 1.316 Collecting wheel==0.24.0
#11 1.357   Downloading wheel-0.24.0-py2.py3-none-any.whl (63 kB)
#11 1.445 Collecting pg8000==1.11.0
#11 1.519   Downloading pg8000-1.11.0-py2.py3-none-any.whl (24 kB)
#11 1.567 Collecting shortuuid==0.4.3
#11 1.758   Downloading shortuuid-0.4.3.tar.gz (6.1 kB)
#11 2.092 Collecting six==1.10.0
#11 2.102   Downloading six-1.10.0-py2.py3-none-any.whl (10 kB)
#11 3.106 Collecting boto3==1.5.3
#11 3.178   Downloading boto3-1.5.3-py2.py3-none-any.whl (128 kB)
#11 3.247 Collecting pgpasslib==1.1.0
#11 3.255   Downloading pgpasslib-1.1.0-py2.py3-none-any.whl (7.8 kB)
#11 3.307 Collecting s3transfer<0.2.0,>=0.1.10
#11 3.316   Downloading s3transfer-0.1.13-py2.py3-none-any.whl (59 kB)
#11 3.376 Collecting jmespath<1.0.0,>=0.7.1
#11 3.385   Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
#11 4.666 Collecting botocore<1.9.0,>=1.8.17
#11 4.686   Downloading botocore-1.8.50-py2.py3-none-any.whl (4.1 MB)
#11 5.533 Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7"
#11 5.542   Downloading futures-3.3.0-py2-none-any.whl (16 kB)
#11 5.609 Collecting python-dateutil<3.0.0,>=2.1
#11 5.621   Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
#11 5.786 Collecting docutils>=0.10
#11 5.809   Downloading docutils-0.18.1-py2.py3-none-any.whl (570 kB)
#11 5.918 Building wheels for collected packages: shortuuid
#11 5.919   Building wheel for shortuuid (setup.py): started
#11 6.209   Building wheel for shortuuid (setup.py): finished with status 'done'
#11 6.209   Created wheel for shortuuid: filename=shortuuid-0.4.3-py2-none-any.whl size=5692 sha256=5db327efc7e4e78ee57b20f570227fbae4184950d0aabf8fbd653f9b01572f5e
#11 6.210   Stored in directory: /root/.cache/pip/wheels/e7/a4/c5/06c4973c9552a19866c2d83ba37c90c48247be2142cd7d9c03
#11 6.210 Successfully built shortuuid
#11 6.251 Installing collected packages: wheel, six, pg8000, shortuuid, futures, python-dateutil, docutils, jmespath, botocore, s3transfer, boto3, pgpasslib
#11 6.252   Attempting uninstall: wheel
#11 6.252     Found existing installation: wheel 0.34.2
#11 6.256     Uninstalling wheel-0.34.2:
#11 6.267       Successfully uninstalled wheel-0.34.2
#11 7.724 Successfully installed boto3-1.5.3 botocore-1.8.50 docutils-0.18.1 futures-3.3.0 jmespath-0.10.0 pg8000-1.11.0 pgpasslib-1.1.0 python-dateutil-2.8.2 s3transfer-0.1.13 shortuuid-0.4.3 six-1.10.0 wheel-0.24.0
#11 7.941 WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
#11 7.941 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
#11 8.164 DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
#11 8.217 Requirement already satisfied: boto3 in /usr/local/lib/python2.7/site-packages (from -r /usr/src/app/UnloadCopyUtility/requirements.txt (line 1)) (1.5.3)
#11 8.472 Collecting pytz
#11 8.505   Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)
#11 8.698 ERROR: Could not find a version that satisfies the requirement redshift_connector[full] (from -r /usr/src/app/UnloadCopyUtility/requirements.txt (line 3)) (from versions: none)
#11 8.713 ERROR: No matching distribution found for redshift_connector[full] (from -r /usr/src/app/UnloadCopyUtility/requirements.txt (line 3))
#11 8.726 WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
#11 8.726 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
------
executor failed running [/bin/sh -c pip install -r /usr/src/app/requirements.txt &&     pip install -r /usr/src/app/UnloadCopyUtility/requirements.txt]: exit code: 1

```

**Comment by timjell** [comment] 2022-08-01 03:05
Thanks for letting us know about this issue. I have updated the Docker build files to fix this. The issue is that we have been moving all the code to Python3, but the docker base image used was an older version so it couldnt install the redshift_connector drivers. This will be fixed shortly when we merge the lastet updated versions shortly.

**Comment by timjell** [comment] 2022-08-01 04:02
Updates have been pushed. If you refresh and rebuild you should be able to execute.

**Closed by timjell** 2022-08-01 04:02 UTC
