### ISSUE TITLE
ImportError: cannot import name MissingQueueError

### ISSUE THREAD

**Issue by dburtsev** [awslabs/amazon-redshift-utils#489] opened 2020-03-10 18:41 UTC
Hello
I am trying to run this script for the first time.
>>> 
*** Remote Interpreter Reinitialized  ***
Traceback (most recent call last):
  File "C:\ColumnEncodingUtility\analyze-schema-compression.py", line 55, in <module>
    import aws_utils
  File "C:\Python27\lib\site-packages\aws_utils\__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "C:\Python27\lib\site-packages\aws_utils\sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError
>>>

**Comment by IanMeyers** [comment] 2020-03-11 11:02
Have you cloned the entire redshift utils repo? This module is a dependency in the parent directory.

**Comment by dburtsev** [comment] 2020-03-11 18:20
Should I modify my path?
>>> 
*** Remote Interpreter Reinitialized  ***
Traceback (most recent call last):
  File "C:\Amazon Redshift Utils\amazon-redshift-utils-master\src\ColumnEncodingUtility\analyze-schema-compression.py", line 61, in <module>
    import aws_utils
  File "C:\Python27\lib\site-packages\aws_utils\__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "C:\Python27\lib\site-packages\aws_utils\sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError
>>>

**Comment by BhuviTheDataGuy** [comment] 2020-04-12 10:05
Im facing the same issue, 

Here is what I did.

Cloned the complete repo.

```
cd amazon-redshift-utils/src/
pip install -r requirements.txt
```
All are installed.

Now when I ran the python code its throwing this error.
```python
Traceback (most recent call last):
  File "analyze_vacuum.py", line 20, in <module>
    import aws_utils
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/__init__.py", line 4, in <module>
    from .sqs_consumer import SQSConsumer  # noqa
  File "/usr/local/lib/python2.7/dist-packages/aws_utils/sqs_consumer.py", line 4, in <module>
    from .exceptions import MissingQueueError
ImportError: cannot import name MissingQueueError
```

**Comment by IanMeyers** [comment] 2020-04-13 12:55
Moving this issue to #495 which is latest. At this time I can't reproduce the issue

**Closed by IanMeyers** 2020-04-13 12:55 UTC
