### ISSUE TITLE
Value too long varchar(275) error with src/AdminViews/v_generate_tbl_ddl.sql

### ISSUE THREAD

**Issue by mattmc3** [awslabs/amazon-redshift-utils#38] opened 2015-08-26 14:16 UTC
When running v_generate_tbl_ddl.sql on certain databases, the script errors with the message:

`ERROR:  value too long for type character varying(275)`

When hacking at the script, I discovered that changing line 77 from this:
`   ,'\t,' + pg_get_constraintdef(con.oid) AS ddl`
to this:
`   ,'\t,' + pg_get_constraintdef(con.oid)::VARCHAR(8000) AS ddl`
addresses the problem for my use case. Unfortunately, I cannot speak to whether this would be the optimal way to solve this for all conditions due to the script's close ties with the deep inner workings of Redshift.

**Comment by ericfe** [comment] 2015-10-31 22:46
Have you tried with other values ( like 1024 instead of 8000 ) ?

**Comment by mattmc3** [comment] 2015-11-02 15:36
8000 is semi-arbitrary. The size just has to be large enough to hold the text of a long FOREIGN KEY object name. 1024 would work until you had a DDL generation for a line needing 1025 characters.

**Comment by ericfe** [comment] 2015-11-02 16:54
Correct.  Given the max size of objects( tables and columns ) 1024 should be enough.
8000 has performance implications. If 1024 works for  you, I will go with that for now.

**Comment by ericfe** [comment] 2016-02-09 01:23
Pushed fix

**Closed by ericfe** 2016-02-09 01:23 UTC

**Comment by matt-mc-aver** [comment] 2016-07-12 21:15
Looks like the problem isn't fixed. The fix should go on line 89 in the `--CONSTRAINT LIST` section of the query. This can be reproduced by adding a UNIQUE constraint on a table using enough columns to blow past 288 characters. The fix is still the same as I described - change line 89 to:
`,'\t,' + pg_get_constraintdef(con.oid)::VARCHAR(1024) AS ddl`
